// Shared content for the Girl Book Club site.
// Covers/photos are placeholders for now — the user will drop in real images,
// and swap the `#` Amazon links for real affiliate URLs.

const BOOKS = [
  {
    id: 'killer',
    title: 'The Killer Among Us',
    author: 'Alice Blake',
    petal: 'rose',
    cover: 'site/covers/killer-among-us.png',
    status: 'testing',
    tag: 'Murder-mystery word search',
    blurb: '40,000 names, 17 clues, one killer. Solve the clues, eliminate the names, and find who did it.',
    long: 'A word-search murder mystery: a grid of 40,000 names hides one killer. Work through 17 clues, strike out every suspect they clear, and the last name standing is your culprit. Part puzzle, part deduction, all tense — the kind of book you finish with a highlighter in hand and a prime suspect in mind.',
    inside: ['A 40,000-name search grid', '17 cryptic clues', 'Suspect-elimination logic', 'A final killer reveal'],
    difficulty: 3,
    stars: 4.5,
    hours: '3–5 days',
    players: '1–4 players',
    pages: 'Paperback puzzle book',
    testers: ['Zlati', 'Dani', 'Ivy'],
    tiktok: 'https://vm.tiktok.com/ZNR3CYBTB/',
    amazon: 'https://www.amazon.com/Killer-Among-Us-murder-mystery/dp/B0H3DZLV5B/',
    amazonLinks: {
      US: 'https://www.amazon.com/Killer-Among-Us-murder-mystery/dp/B0H3DZLV5B/',
      UK: 'https://www.amazon.co.uk/Killer-Among-Us-murder-mystery/dp/B0H3DZLV5B/',
      AU: 'https://www.amazon.com.au/Killer-Among-Us-murder-mystery/dp/B0H3DZLV5B/',
      NL: 'https://www.amazon.nl/Killer-Among-Us-murder-mystery/dp/B0H3DZLV5B/',
    },
    verdict: 'A clever twist on the word search — gripping once the eliminations start. (Edit this with the club’s real take!)',
  },
  {
    id: 'rosewood',
    title: 'Murder Mystery Word Search: The Rosewood Files',
    author: 'Melanie Collins',
    petal: 'berry',
    cover: 'site/covers/rosewood-files.png',
    tag: 'Murder-mystery word search',
    blurb: '105 cases to solve. Find the clues, connect the evidence, and catch the killer in every puzzle.',
    long: 'A whole case file of murder-mystery word searches — 105 cases in all. Each one hides the victim, the killer and the motive in the grid; find the clues, connect the evidence and name your culprit before turning the page. Cozy-noir to its core, with detective notes and a satisfying reveal every time. The perfect rainy-afternoon companion for a mystery lover.',
    inside: ['105 self-contained cases', 'Victim · killer · motive grids', 'Detective-notes clue trail', 'A reveal for every case'],
    difficulty: 2,
    stars: 5,
    hours: 'A case a day',
    players: '1–4 players',
    pages: '105 cases · paperback',
    testers: ['Ivy', 'Zlati', 'Dani'],
    tiktok: 'https://vm.tiktok.com/ZNR3CyD2N/',
    amazon: 'https://www.amazon.com/Murder-Mystery-Search-Rosewood-Files/dp/B0H4YQP39S/',
    amazonLinks: {
      US: 'https://www.amazon.com/Murder-Mystery-Search-Rosewood-Files/dp/B0H4YQP39S/',
      UK: 'https://www.amazon.co.uk/Murder-Mystery-Search-Rosewood-Files/dp/B0H4YQP39S/',
      AU: 'https://www.amazon.com.au/Murder-Mystery-Search-Rosewood-Files/dp/B0H4YQP39S/',
      NL: 'https://www.amazon.nl/Murder-Mystery-Search-Rosewood-Files/dp/B0H4YQP39S/',
    },
    verdict: 'So many cases you’ll never run out. Cozy, moreish, perfect for a mystery lover. (Swap in the club’s real take!)',
  },
  {
    id: 'whozzle',
    title: 'Whozzle: Murder Mystery for 1',
    author: 'Catherine Casey',
    petal: 'berry',
    cover: 'site/covers/whozzle.png',
    tag: 'Logic-grid whodunnit',
    blurb: '80 logic puzzles. Read the clues, work the grid, and deduce the killer — one solo case at a time.',
    long: 'Read. Deduce. Solve. Whozzle is 80 self-contained logic-grid whodunnits built for a solo sleuth. Each case lines up suspects, a crime board and a logic grid — cross-reference the clues, fill the yes/no grid, and corner the killer. Pure deduction with no setup and no fuss: just you, a pencil and a body in the library at 9:15 PM.',
    inside: ['80 logic-grid cases', 'Suspect line-ups', 'Crime-board clue spreads', 'Yes/no deduction grids'],
    difficulty: 3,
    stars: 4.5,
    hours: 'A case a day',
    players: '1 player',
    pages: '80 puzzles · Volume 1',
    testers: ['Zlati', 'Dani'],
    tiktok: 'https://vm.tiktok.com/ZNR3CD71J/',
    amazon: 'https://www.amazon.com/Whozzle-Murder-Mystery-Catherine-Casey/dp/B0H4W2MC17/',
    amazonLinks: {
      US: 'https://www.amazon.com/Whozzle-Murder-Mystery-Catherine-Casey/dp/B0H4W2MC17/',
      UK: 'https://www.amazon.co.uk/Whozzle-Murder-Mystery-Catherine-Casey/dp/B0H4W2MC17/',
      AU: 'https://www.amazon.com.au/Whozzle-Murder-Mystery-Catherine-Casey/dp/B0H4W2MC17/',
      NL: 'https://www.amazon.nl/Whozzle-Murder-Mystery-Catherine-Casey/dp/B0H4W2MC17/',
    },
    verdict: 'The best solo puzzle book on the shelf — pure deduction, no setup. (Swap in the club’s real take!)',
  },
  {
    id: 'colorsudoku',
    title: 'Color Sudoku',
    author: 'Alice Blake',
    petal: 'mint',
    cover: 'site/covers/color-sudoku.png',
    tag: 'Colour logic · sudoku',
    blurb: 'Sudoku with colours instead of numbers — 180 puzzles. Same satisfying logic, a brighter, friendlier twist.',
    long: 'A fresh spin on the classic: fill every row, column and box so no colour repeats — no numbers needed. It plays exactly like number sudoku but reads as a calmer, brighter puzzle, lovely for anyone who finds a grid of numbers off-putting. 180 puzzles graded from easy to fiendish make it the relaxing palate-cleanser between our murder mysteries — boost your mind, improve focus, and unwind.',
    inside: ['180 colour-grid puzzles', 'No numbers — pure colour logic', 'Easy-to-fiendish grading', 'A calming, bright layout'],
    difficulty: 2,
    stars: 4.5,
    hours: 'A puzzle a day',
    players: '1 player',
    pages: '180 puzzles · paperback',
    testers: ['Ivy', 'Zlati'],
    tiktok: 'https://vm.tiktok.com/ZNR3CYAAR/',
    amazon: 'https://www.amazon.com/Color-Sudoku-Alice-Blake/dp/B0H3GYFQFM/',
    amazonLinks: {
      US: 'https://www.amazon.com/Color-Sudoku-Alice-Blake/dp/B0H3GYFQFM/',
      UK: 'https://www.amazon.co.uk/Color-Sudoku-Alice-Blake/dp/B0H3GYFQFM/',
      AU: 'https://www.amazon.com.au/Color-Sudoku-Alice-Blake/dp/B0H3GYFQFM/',
      NL: 'https://www.amazon.nl/Color-Sudoku-Alice-Blake/dp/B0H3GYFQFM/',
    },
    verdict: 'Our relaxing in-between book. Bright, calming, quietly addictive. (Swap in the club’s real take!)',
  },
];

// The club members ("the girls") — tagline: Good books. Sharp minds. Perfect day.
const GIRLS = [
  { name: 'Zlati', initial: 'Z', role: 'The Clue Queen', photo: 'site/photos/zlati.png',
    bio: 'It’s not luck, it’s logic. Zlati started the club and still calls the shots — happiest on the page where it turns tricky and you have to think like a real detective.', fav: 'killer' },
  { name: 'Dani', initial: 'D', role: 'Logic Fox', photo: 'site/photos/dani.png',
    bio: 'Reads every clue twice and the room once. Never in a hurry — she’d rather savour a good twist with a coffee than rush to the answer.', fav: 'rosewood' },
  { name: 'Ivy', initial: 'I', role: 'Puzzle Ninja', photo: 'site/photos/ivy.png',
    bio: 'Quietly solves the grid while everyone’s still arguing. In it for the cosy evenings, the calm focus and the satisfying click when it all comes together.', fav: 'colorsudoku' },
];

// Reviews/comments, tied to books by id.
const REVIEWS = [
  { book: 'killer', name: 'Zlati', club: true, stars: 4.5,
    text: 'Currently halfway through — the eliminations get properly tense once you’re down to a handful of names. Early notes only!' },
  { book: 'killer', name: 'PuzzleNell', club: false, stars: 5,
    text: 'Such a clever idea. I keep second-guessing which name to strike out. Can’t wait for the club’s full verdict.' },
  { book: 'rosewood', name: 'Ivy', club: true, stars: 5,
    text: 'So many cases you’ll never run out. Cozy-noir comfort — my go-to for a rainy afternoon with tea.' },
  { book: 'rosewood', name: 'GardenPartyGill', club: false, stars: 5,
    text: 'Bought it after your review and we’re hooked. The detective-notes clue trail is genuinely satisfying.' },
  { book: 'whozzle', name: 'Dani', club: true, stars: 4.5,
    text: 'A lovely slow burn — we take one case an evening and really sink into the deduction. No setup, just you, a cuppa and a proper little mystery.' },
  { book: 'whozzle', name: 'inkandowl', club: false, stars: 4,
    text: 'Loved that it’s built for one player. Some grids fooled me completely until the last clue. Brilliant.' },
  { book: 'colorsudoku', name: 'Zlati', club: true, stars: 4.5,
    text: 'Our relaxing in-between book. Colours instead of numbers is weirdly calming — quietly addictive.' },
  { book: 'colorsudoku', name: 'ReadingWithRu', club: false, stars: 4.5,
    text: 'Perfect for someone who finds number sudoku off-putting. Bright, friendly and surprisingly tricky higher up.' },
];

const reviewsFor = (id) => REVIEWS.filter(r => r.book === id);
const bookById = (id) => BOOKS.find(b => b.id === id) || BOOKS[0];

// Merch — "Puzzle Girls Club" line. Prices are placeholders; `link` empty → "Coming soon".
const MERCH = [
  { id: 'hoodie', name: '“Puzzle Therapy” Hoodie', img: 'site/merch/hoodie.png',
    tag: 'Read. Think. Solve. Repeat.', price: '$42', blurb: 'Soft rose hoodie, front + back print. The cosiest way to puzzle.', petal: 'rose', link: '', wide: true },
  { id: 'tee', name: 'Oversized Club Tee', img: 'site/merch/tee.png',
    tag: 'Coffee · Books · Logic', price: '$28', blurb: 'Relaxed-fit tee with the club crest front and the mantra on the back.', petal: 'berry', link: '' },
  { id: 'mugs', name: 'Statement Mugs', img: 'site/merch/mugs.png',
    tag: '4 designs', price: '$14', blurb: '“Clues before coffee.” Pick your character — Clue Queen, Logic Fox, Puzzle Ninja.', petal: 'lav', link: '' },
  { id: 'notebooks', name: 'Character Notebooks', img: 'site/merch/notebooks.png',
    tag: '3 designs', price: '$12', blurb: 'Clue Queen, Logic Fox or Puzzle Ninja — for notes, theories & suspects.', petal: 'coral', link: '' },
  { id: 'tote', name: '“I Have Plans” Tote', img: 'site/merch/tote.png',
    tag: 'Coffee · Puzzle Book · Ignore Everyone', price: '$16', blurb: 'Sturdy canvas tote for your books, snacks and zero social plans.', petal: 'honey', link: '' },
  { id: 'sleeve', name: '“Clues Inside” Book Sleeve', img: 'site/merch/sleeve.png',
    tag: 'Handle with coffee', price: '$18', blurb: 'Padded sleeve that keeps your current puzzle book safe in any bag.', petal: 'rose', link: '' },
  { id: 'stickers', name: 'Sticker Pack', img: 'site/merch/stickers.png',
    tag: '8 stickers', price: '$6', blurb: '“Before coffee”, “Brain loading…”, character badges & more.', petal: 'mint', link: '' },
  { id: 'bookmarks', name: 'Tasselled Bookmarks', img: 'site/merch/bookmarks.png',
    tag: 'Set of 3', price: '$8', blurb: '“Every clue matters.” Pretty tassels, gentle reminders.', petal: 'sky', link: '' },
  { id: 'pens', name: 'Click Pen Set', img: 'site/merch/pens.png',
    tag: 'Set of 4', price: '$10', blurb: 'Pink Logic, Clue Hunter, Brain Fuel & Solve Mode On.', petal: 'berry', link: '' },
  { id: 'markers', name: 'Acrylic Marker Set', img: 'site/merch/markers.png',
    tag: 'Set of 6', price: '$15', blurb: 'Perfect for puzzles & notes — six club colours that pop on any page.', petal: 'coral', link: '' },
  { id: 'socks', name: '“Read / Solve” Socks', img: 'site/merch/socks.png',
    tag: '2 pairs', price: '$9', blurb: 'One says READ, one says SOLVE. For very important puzzle days.', petal: 'lav', link: '' },
];

// The club's TikTok videos (short links resolve automatically on the live site).
const VIDEOS = [
  'https://vm.tiktok.com/ZNR3CYBTB/',
  'https://vm.tiktok.com/ZNR3CyD2N/',
  'https://vm.tiktok.com/ZNR3CD71J/',
  'https://vm.tiktok.com/ZNR3CYAAR/',
  'https://vm.tiktok.com/ZNR3Cf38b/',
  'https://vm.tiktok.com/ZNR3CAath/',
  'https://vm.tiktok.com/ZNR3CP58N/',
  'https://vm.tiktok.com/ZNR3CA9Ku/',
  'https://vm.tiktok.com/ZNR3C88uv/',
  'https://vm.tiktok.com/ZNR3CjqG4/',
  'https://vm.tiktok.com/ZNR3CLL3K/',
  'https://vm.tiktok.com/ZNR3CeCVk/',
  'https://vm.tiktok.com/ZNR3CUNgP/',
  'https://vm.tiktok.com/ZNR3CD7PC/',
];

Object.assign(window, { BOOKS, GIRLS, REVIEWS, VIDEOS, MERCH, reviewsFor, bookById });
